public enum LeapFeatureEnum : int
{
    // Left Hand
    LeftHandDirMagnitude,
    LeftHandSqrMagnitude,
    LeftHandDirectionX,
    LeftHandDirectionY,
    LeftHandDirectionZ,
    LeftWristX,
    LeftWristY,
    LeftWristZ,

    LeftArmLength,
    LeftArmWidth,
    LeftArmCenterX,
    LeftArmCenterY,
    LeftArmCenterZ,
    LeftArmElbowPositionX,
    LeftArmElbowPositionY,
    LeftArmElbowPositionZ,

    LeftPalmPositionX,
    LeftPalmPositionY,
    LeftPalmPositionZ,

    LeftPalmVelocityX,
    LeftPalmVelocityY,
    LeftPalmVelocityZ,
    LeftPalmVelocityMagnitude,


LeftPalmNormalX,
LeftPalmNormalY,
LeftPalmNormalZ,
LeftPalmNormalMagnitude,

    LeftThumbTipX,
    LeftThumbTipY,
    LeftThumbTipZ,
    LeftThumbLength,
    LeftThumbMetacarpalX,
    LeftThumbMetacarpalY,
    LeftThumbMetacarpalZ,
    LeftThumbProximalX,
    LeftThumbProximalY,
    LeftThumbProximalZ,
    LeftThumbIntermediateX,
    LeftThumbIntermediateY,
    LeftThumbIntermediateZ,
    LeftThumbDistalX,
    LeftThumbDistalY,
    LeftThumbDistalZ,

    LeftIndexTipX,
    LeftIndexTipY,
    LeftIndexTipZ,
    LeftIndexLength,

    LeftIndexMetacarpalX,
    LeftIndexMetacarpalY,
    LeftIndexMetacarpalZ,
    LeftIndexProximalX,
    LeftIndexProximalY,
    LeftIndexProximalZ,
    LeftIndexIntermediateX,
    LeftIndexIntermediateY,
    LeftIndexIntermediateZ,
    LeftIndexDistalX,
    LeftIndexDistalY,
    LeftIndexDistalZ,

    LeftMiddleTipX,
    LeftMiddleTipY,
    LeftMiddleTipZ,
    LeftMiddleLength,

    LeftMiddleMetacarpalX,
    LeftMiddleMetacarpalY,
    LeftMiddleMetacarpalZ,
    LeftMiddleProximalX,
    LeftMiddleProximalY,
    LeftMiddleProximalZ,
    LeftMiddleIntermediateX,
    LeftMiddleIntermediateY,
    LeftMiddleIntermediateZ,
    LeftMiddleDistalX,
    LeftMiddleDistalY,
    LeftMiddleDistalZ,

    LeftRingTipX,
    LeftRingTipY,
    LeftRingTipZ,
    LeftRingLength,
    LeftRingMetacarpalX,
    LeftRingMetacarpalY,
    LeftRingMetacarpalZ,
    LeftRingProximalX,
    LeftRingProximalY,
    LeftRingProximalZ,
    LeftRingIntermediateX,
    LeftRingIntermediateY,
    LeftRingIntermediateZ,
    LeftRingDistalX,
    LeftRingDistalY,
    LeftRingDistalZ,

    LeftPinkyTipX,
    LeftPinkyTipY,
    LeftPinkyTipZ,
    LeftPinkyLength,
    LeftPinkyMetacarpalX,
    LeftPinkyMetacarpalY,
    LeftPinkyMetacarpalZ,
    LeftPinkyProximalX,
    LeftPinkyProximalY,
    LeftPinkyProximalZ,
    LeftPinkyIntermediateX,
    LeftPinkyIntermediateY,
    LeftPinkyIntermediateZ,
    LeftPinkyDistalX,
    LeftPinkyDistalY,
    LeftPinkyDistalZ,

    // Right Hand
    RightHandDirMagnitude,
    RightHandSqrMagnitude,
    RightHandDirectionX,
    RightHandDirectionY,
    RightHandDirectionZ,
    RightWristX,
    RightWristY,
    RightWristZ,

    RightArmLength,
    RightArmWidth,
    RightArmCenterX,
    RightArmCenterY,
    RightArmCenterZ,
    RightArmElbowPositionX,
    RightArmElbowPositionY,
    RightArmElbowPositionZ,

    RightPalmPositionX,
    RightPalmPositionY,
    RightPalmPositionZ,
    RightPalmVelocityX,
    RightPalmVelocityY,
    RightPalmVelocityZ,
    RightPalmVelocityMagnitude,


RightPalmNormalX,
RightPalmNormalY,
RightPalmNormalZ,
RightPalmNormalMagnitude,




    RightThumbTipX,
    RightThumbTipY,
    RightThumbTipZ,
    RightThumbLength,
    RightThumbMetacarpalX,
    RightThumbMetacarpalY,
    RightThumbMetacarpalZ,
    RightThumbProximalX,
    RightThumbProximalY,
    RightThumbProximalZ,
    RightThumbIntermediateX,
    RightThumbIntermediateY,
    RightThumbIntermediateZ,
    RightThumbDistalX,
    RightThumbDistalY,
    RightThumbDistalZ,

    RightIndexTipX,
    RightIndexTipY,
    RightIndexTipZ,
    RightIndexLength,
    RightIndexMetacarpalX,
    RightIndexMetacarpalY,
    RightIndexMetacarpalZ,
    RightIndexProximalX,
    RightIndexProximalY,
    RightIndexProximalZ,
    RightIndexIntermediateX,
    RightIndexIntermediateY,
    RightIndexIntermediateZ,
    RightIndexDistalX,
    RightIndexDistalY,
    RightIndexDistalZ,

    RightMiddleTipX,
    RightMiddleTipY,
    RightMiddleTipZ,
    RightMiddleLength,

    RightMiddleMetacarpalX,
    RightMiddleMetacarpalY,
    RightMiddleMetacarpalZ,
    RightMiddleProximalX,
    RightMiddleProximalY,
    RightMiddleProximalZ,
    RightMiddleIntermediateX,
    RightMiddleIntermediateY,
    RightMiddleIntermediateZ,
    RightMiddleDistalX,
    RightMiddleDistalY,
    RightMiddleDistalZ,

    RightRingTipX,
    RightRingTipY,
    RightRingTipZ,
    RightRingLength,
    RightRingMetacarpalX,
    RightRingMetacarpalY,
    RightRingMetacarpalZ,
    RightRingProximalX,
    RightRingProximalY,
    RightRingProximalZ,
    RightRingIntermediateX,
    RightRingIntermediateY,
    RightRingIntermediateZ,
    RightRingDistalX,
    RightRingDistalY,
    RightRingDistalZ,

    RightPinkyTipX,
    RightPinkyTipY,
    RightPinkyTipZ,
    RightPinkyLength,
    RightPinkyMetacarpalX,
    RightPinkyMetacarpalY,
    RightPinkyMetacarpalZ,
    RightPinkyProximalX,
    RightPinkyProximalY,
    RightPinkyProximalZ,
    RightPinkyIntermediateX,
    RightPinkyIntermediateY,
    RightPinkyIntermediateZ,
    RightPinkyDistalX,
    RightPinkyDistalY,
    RightPinkyDistalZ,
}
